[package]
name = "cni"
version = "0.3.0"
authors = ["Johann150 <johann+cni@qwertqwefsday.eu>"]
edition = "2018"
description = "parser for the CNI configuration format"
readme = "README.md"
repository = "https://github.com/Johann150/cni"
license = "Unlicense"
keywords = ["configuration", "ini", "cni"]
categories = ["config", "encoding", "parser-implementations"]
exclude = ["src/tests/**"]

[dependencies]

[dev-dependencies]
serde_json = "1.0"

[features]
default = ["ini", "flexspace", "tabulation"]
# enables the INI compatibility `ini`
ini = []
# enables ext `flexspace`
# because the library does not backtrack, this also contains ext tabulation's
# functionality. To make this explicit, it is also enabled.
flexspace = ["tabulation"]
# enables ext `tabulation`
tabulation = []
