[package]
name = "cni"
version = "0.1.0"
authors = ["Johann150 <johann+cni@qwertqwefsday.eu>"]
edition = "2018"
license = "Unlicense"
readme = "README.md"
exclude = ["src/tests/**"]

[dependencies]

[dev-dependencies]
serde_json = "1.0"
